### ISSUE TITLE
Error (Do not know)

### ISSUE THREAD

**Issue by tommyp6** [tjguk/email2wf#1]
I get a error at `import email.parser` because it is not installed, and I run `pip3 install email` but I get the following error :
![screenshot from 2018-11-22 17-35-05](https://user-images.githubusercontent.com/43862943/48917114-0f4fa280-ee7d-11e8-8902-73a0a95eeac7.png)
 I looked at Google & GitHub for the following error but I can' t solve it.

I tried `pip3 install --upgrade setuptools` and I get this output : `Requirement already up-to-date: setuptools in ./.local/lib/python3.6/site-packages (40.6.2)`

**Comment by tjguk** [comment]
Strange, because email.parser is built in to Python3:

https://docs.python.org/3/library/email.parser.html

But I'm not even sure it's trying to import email because my code doesn't use that at all!

Can you show me the command line you're running?

**Comment by tommyp6** [comment]
I get this : 
![screenshot from 2018-11-22 19-07-40](https://user-images.githubusercontent.com/43862943/48919310-f0a3d880-ee89-11e8-870c-986172afed88.png)

I don' t know how to fix it.

**Comment by tjguk** [comment]
@TommyPujol06 I can't see exactly, but I suspect that you've created a file called email.py with my code in it. If so, this is shadowing the built-in email module (which, for some reason indirectly by the xmlrpc lib). Try renaming the file to something else. (emailtp.py for example) and try again

**Comment by tommyp6** [comment]
It solved it :+1: . But it happend something else : 
![screenshot from 2018-11-22 20-23-40](https://user-images.githubusercontent.com/43862943/48921022-9c522600-ee94-11e8-8c57-0afc2c9d5ec8.png)

**Comment by tjguk** [comment]
Before you go too far @TommyPujol06 you won't be able to run the code fully because you need an account on my hosting provider (webfaction.com). I'm sorry for not making that clear. 

However I realise from seeing your error that I should have updated the comment in the code which indicates the structure of the .ini file. I'll do what I usually do with an .ini file: create a master copy which is versioned and which contains the structure and no data. I can copy it and insert the right values. (However you won't be able to unless you pay webfaction.com for a hosting account!)

**Comment by tjguk** [comment]
I've just added a master .ini file with the structure but without the data:

https://github.com/tjguk/email2wf/blob/master/text2email.master.ini

**Comment by tommyp6** [comment]
I created an account but it says that I am not authorized : 
![screenshot from 2018-11-22 20-44-06](https://user-images.githubusercontent.com/43862943/48921406-7f6b2200-ee97-11e8-9f5b-ebc2f8e4b16b.png)

**Comment by tjguk** [comment]
That's probably because you need to specify the underlying web server, not the domain name. But perhaps we can look at this on Saturday if you want to pursue it...?

**Comment by tommyp6** [comment]
OK
